# Generated by Django 2.0.4 on 2018-04-19 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0003_auto_20180419_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_void', models.BooleanField(default=False)),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalogue.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book favorite',
                'verbose_name_plural': 'Book favorites',
                'default_related_name': 'favorites',
            },
        ),
        migrations.RemoveField(
            model_name='usertobookrelations',
            name='book',
        ),
        migrations.RemoveField(
            model_name='usertobookrelations',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserToBookRelations',
        ),
    ]
